"""make unique rider last name

Revision ID: 340a3902abce
Revises: d86bc14a477b
Create Date: 2021-06-06 20:57:49.279749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340a3902abce'
down_revision = 'd86bc14a477b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'riders', ['last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riders', type_='unique')
    # ### end Alembic commands ###
