"""add many to many relation for tables bikes and riders

Revision ID: ae39509ca0f3
Revises: 340a3902abce
Create Date: 2021-06-08 16:40:21.570475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae39509ca0f3'
down_revision = '340a3902abce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_riders',
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('rider_id', 'bike_id')
    )
    op.create_unique_constraint(None, 'riders', ['last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riders', type_='unique')
    op.drop_table('bike_riders')
    # ### end Alembic commands ###
